# Workflow for ECO's continuous integration testing

name: ECO Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  eco_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: CI Test
        run: |
          make test
